<?php
// CP
if (($this->getMode() == 2) && $this->getRetailerId() && $this->isEnabled()) : 
	// signed in so show elist
	if ($this->getCustomerEmail()):
?>
<iframe 
    id="streamIFrame" 
    name="streamIFrame" 
    src="https://www.cueconnect.com/poweredby/<?php echo $this->getRetailerId() ?>/?origin=<?php echo Mage::getBaseUrl(); ?>&amp;version=embed&amp;from=stream&amp;email=<?php echo $this->getCustomerEmail() ?>" 
    height="640px" 
    width="100%" 
    scrolling="no"
    style="
        border:none;
        display:block;
        width:100%;
        max-width:1000px;
        margin: 0 auto 1em;
    "></iframe>
<?php 
    // show prelogin
    else:
?>
    <!-- BEGIN Cue e-List -->
    <style>

    #cue-magento-forms-container iframe {border: none;}

    #cue-magento-forms-container{
        display: table;
        table-layout: fixed;
        width: 100%;
        padding: 2em 0 4em 0;
        margin: auto;
    }

    #cue-magento-forms-container h1,
    #cue-magento-forms-container h2,
    #cue-magento-forms-container h3 {
        font-size: 2em;
        border:none;
        font-weight: normal;
        display:block;
        line-height: 1.5em;
        margin: 0 0 1em 0;
    }

    #cue-magento-forms-container .legend {
        display:none;
    }

    #cue-magento-forms-container p {
        margin: 0 0 1em 0;
        line-height: 1.5em;
    }

    #cue-magento-forms-container ul,
    #cue-magento-forms-container ol {
        margin: 0 0 1em 0;
        line-height: 1.5em;
        padding: 0 0 0 1.5em;
        list-style: disc;
    }

    #cue-magento-forms-container ul li {
        line-height: 1.5em;        
    }

    #cue-magento-forms-container ul.form-list {
        padding: 0;
        list-style:none;
    }

    #cue-magento-forms-container label {
        background:none;
    }

    #cue-magento-forms-container .buttons-set {
        text-align: inherit;
        clear:both;
        border:none;
        margin: 1em 0;
        padding: 0;
    }

    #cue-magento-forms-container .buttons-set p.required {
        float:none;
        display:block;
    }

    #cue-magento-forms-container .buttons-set a {
        float:none !important;
        display:block;
        line-height: 1.5em;
        margin-bottom: 1em;
        padding:0;
    }

    #cue-magento-forms-container .buttons-set button.button {
        float:inherit;
        clear:both;
        display:block;
        margin: 0;
        min-width:10em;
    }

    .cue-info-container,
    .cue-auth-container{
        display: table-cell;
        text-align: left;
        width:50%;
    }

    #cue-magento-forms-container #recover-password {
        display:none;
    }

    .cue-auth-container input[type="text"],
    .cue-auth-container input[type="email"],
    .cue-auth-container input[type="password"] {
        display:inline-block;
        width: 20em;
        max-width:100%;
    }

    @media screen and (max-width: 798px){
        #cue-magento-forms-container {
            display:block;
        }
        #cue-magento-forms-container input {
            width: 100%;
        }
        .cue-auth-container,
        .cue-info-container{
            display: block;
            width: 100%;
        }
    }
   
</style>

<!-- user is not authenticated -->
<div  id="cue-magento-forms-container">
    <div class="cue-info-container">
        <h2 class="title cue-title">Welcome to My List</h2>
        <p>Everything you care about in one place. Built just for you.</p>
        <ul>
            <li>Wishlist items</li>
            <li>Shares and Posts you want to remember</li>
            <li>Price Alerts on items you care about</li>
            <li>Special offers and rewards</li>
            <li>Always on, always available</li>
        </ul>
        <p>Goodbye forgetting. Hello remembering</p>
    </div>

    <div class="cue-auth-container">
        <!-- register form START -->
        <div id="customer-register" class="cue-form-container" style="display: none;">
            <div class="">
                <div id="register" class="">
                    <h2 class="title cue-title">Create Account</h2>
                    <?php echo $this->getChildHtml('customer_form_register') ?>
                </div><!-- #register -->
            </div><!-- .row -->
        </div><!-- #customer-register -->
        <!-- register form END -->


        <!-- login form START -->
        <div id="customer-login" class="cue-form-container">
            <div class="">
                <div id="login" class="">
                    <h2 class="title cue-title">Login</h2>
                    <?php echo $this->getChildHtml('customer_form_login') ?>
                </div>

                <div id="recover-password" class="cue-forgot-pswd-container">
                	<?php echo $this->getChildHtml('forgotPassword') ?>
                </div>

            </div>
        </div>

        <script type="text/javascript">
            function showRecoverPasswordForm() {
                document.getElementById('recover-password').style.display = 'block';
                document.getElementById('login').style.display='none';
            }

            function hideRecoverPasswordForm() {
                document.getElementById('recover-password').style.display = 'none';
                document.getElementById('login').style.display = 'block';
            }

            if (window.location.hash == '#recover') { showRecoverPasswordForm() }
        </script>
        <!-- login form END -->

        <p  id="cue-show-signup" >Don't have an account? <a href="#" onclick="cueShowSignup();return false;">Sign up</a></p>

        <script>
            function cueShowSignup(){
                document.getElementById('cue-show-signup').style.display = 'none';
                document.getElementById('customer-login').style.display = 'none';
                document.getElementById('customer-register').style.display = 'block';
                console.log(this);
            }

            function cueShowSignin(){
                document.getElementById('customer-register').style.display = 'none';
                document.getElementById('customer-login').style.display = 'block';
                document.getElementById('cue-show-signup').style.display = 'block';
            }

            var pid = <?php echo ($this->getRetailerId()) ? $this->getRetailerId() : 0 ; ?>;
        </script>
    </div>
</div>
<!-- END Cue e-List -->
<?php
	endif;
endif; 
?>

