<?php if ($this->isEnabled() && $this->getRetailerId()): ?>

<script src="https://stream.cueconnect.com/js/cue-seed.js"></script>
<script>
function doLoad() {
  CUE({
     'retailId': <?php echo $this->getRetailerId(); ?>,
     'apiKey': '<?php echo $this->getApiKey(); ?>',
     'cid': <?php echo $this->getCID(); ?>,
     'path': '<?php echo $this->getElistPath() ?>'
  });
}
if ( window.addEventListener ) { 
  window.addEventListener( "load", doLoad, false );
} else if ( window.attachEvent ) { 
  window.attachEvent( "onload", doLoad );
} else if ( window.onLoad ) {
  window.onload = doLoad;
}
</script>

<?php endif; ?>
