<?php
/**
 * CueConnect_Cue
 *
 * @category    CueConnect
 * @package     CueConnect_Cue
 * @copyright   Copyright (c) 2015 Cue Connect
 * @author      Cue Connect (http://www.cueconnect.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var $this CueConnect_Cue_Block_Checkout_Success_Share
 */
?>

<?php if ($this->isEnabled() && $this->getRetailerId() && $this->getFirstProductSku()): ?>
    <!-- share button (widget) -->
    <div class="cue-onebutton" data-imisku="<?php echo $this->escapeHtml($this->getFirstProductSku()) ?>"></div>
    <?php if ($this->isTrackingEnabled()): ?>
        <!-- Cue Conversion Tracking START -->
        <img height="1" width="1" src="<?php echo $this->getTrackingSource() ?>" style="display:none"/>
        <!-- Cue Conversion Tracking END -->
    <?php endif; ?>
<?php endif; ?>